"""add posts & follows tables

Revision ID: 6c42ac87471e
Revises: 2b471dcf028a
Create Date: 2026-07-05 22:39:40.292108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c42ac87471e'
down_revision: Union[str, Sequence[str], None] = '2b471dcf028a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('body', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('PUBLIC', 'PRIVATE', name='poststatus'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('posts')
    # ### end Alembic commands ###
