"""add user_id image location to posts

Revision ID: ed9b7fd50278
Revises: 6c42ac87471e
Create Date: 2026-08-01 22:00:12.060207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9b7fd50278'
down_revision: Union[str, Sequence[str], None] = '6c42ac87471e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('posts', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('location', sa.String(length=255), nullable=True))
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'body',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('posts', 'location')
    op.drop_column('posts', 'image')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
